-- 查询系统表生成表字典(默认值需要单独处理)
USE information_schema;

SELECT
	T.TABLE_NAME AS '表名',
	T.TABLE_COMMENT AS '表说明',
	C.COLUMN_NAME AS '字段名',
	C.COLUMN_TYPE AS '类型',
	(
		CASE
		WHEN (
			SELECT
				COUNT(1)
			FROM
				INFORMATION_SCHEMA.KEY_COLUMN_USAGE
			WHERE
				TABLE_SCHEMA = T.TABLE_SCHEMA
			AND TABLE_NAME = T.TABLE_NAME
			AND COLUMN_NAME = C.COLUMN_NAME
			LIMIT 0,
			1
		) = 0 THEN
			''
		ELSE
			'YES'
		END
	) AS '主键',
	(
		CASE
		WHEN C.IS_NULLABLE = 'YES' THEN
			''
		ELSE
			'YES'
		END
	) AS '不为空',
	'NULL' AS '默认值',
	C.COLUMN_COMMENT AS '注释'
FROM
	COLUMNS C
LEFT JOIN TABLES T ON C.TABLE_SCHEMA = T.TABLE_SCHEMA
AND C.TABLE_NAME = T.TABLE_NAME
WHERE
	T.TABLE_SCHEMA = '@DataBaseName'
AND T.TABLE_NAME IN ('@TableName')
ORDER BY
	T.TABLE_NAME,
	C.ORDINAL_POSITION